### ISSUE TITLE
Is this possible to download the data just providing the name.

### ISSUE THREAD

**Issue by yashanand** [projectdiscovery/chaos-client#33]
Like provide only the target Netflix and it will fetch all the dataset which belong to the Netflix.
Currently, I am doing like this
chaos -d netflix.com
chaos -d nflxext.com
chaos -d nflximg.net
chaos -d nflxso.net
chaos -d nflxvideo.net

**Comment by bauthard** [comment]
Hi @yashanand, 

The project name is something for better UX while using the website, but we do not cluster or maintain list based on project name at the backend, so it's not possible for now, another alternative for this is https://github.com/dr-0x0x/chaospy, which let you download data based on filters, instead of program name, give a try. 

Closing this for now.
